version: '3.8'

services:
  checkrpc:
    build:
      context: .
      dockerfile: ./rpc/check/Dockerfile
    # image: checkrpc:0.0.1
    expose:
      - 8083
    ports:
      - "8083:8083"
      - "8091:8091"
    volumes:
      - ./:/app

  addrpc:
    build:
      context: .
      dockerfile: ./rpc/add/Dockerfile
    # image: addrpc:0.0.1
    expose:
      - 8082
    ports:
      - "8082:8082"
      - "8090:8090"
    volumes:
      - ./:/app
    depends_on:
      - checkrpc

  changerpc:
    build:
      context: .
      dockerfile: ./rpc/change/Dockerfile
    # image: changerpc:0.0.1
    expose:
      - 8084
    ports:
      - "8084:8084"
      - "8092:8092"
    volumes:
      - ./:/app
    depends_on:
      - checkrpc
  
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    # image: apirpc:0.0.1
    expose:
      - 8888
    ports:
      - "8888:8888"
      - "8898:8898"
    volumes:
      - ./:/app
    depends_on:
      - addrpc
      - checkrpc
      - changerpc
  


