// Code generated by goctl. DO NOT EDIT!
// Source: check.proto

package changer

type (
	ChangeReq struct {
		Book  string `json:"book,omitempty"`
		Price int64  `json:"price,omitempty"`
	}

	ChangeResp struct {
		Ok bool `json:"ok,omitempty"`
	}
)
